### ISSUE TITLE
Join the ExtendScript org?

### ISSUE THREAD

**Issue by fabiantheblind** [majman/adobe-scripts-panel#1]
Hi I've invited you to our ExtendScript org here on GitHub. You can accept or decline that invite here https://github.com/ExtendScript

If you want to know more about the org take a look at this [repository](https://github.com/ExtendScript/about). There are no strings attached. If you don't have time to contribute - don't worry. You can still join. Having more members means we can make a bigger impact on Adobe. 

Cheers
Fabian

**Comment by majman** [comment]
Fun! Had no idea such an org existed. Thanks for the invite :)

**Comment by fabiantheblind** [comment]
We started some days ago. Feel free to invite more Adobe script authors

**Comment by majman** [comment]
@fabiantheblind will do!
