### ISSUE TITLE
Error with folders

### ISSUE THREAD

**Issue by SoskiKrota** [majman/adobe-scripts-panel#3]
Hi, i got a little issue with the plugin.
To organize my scripts better i created some folders inside my scripts main folder. But when i tried to use them i got this error message:

Sorry, it appears that this script file cannot be located at "C:\Program Files\Adobe\Adobe Illustrator CC 2017\Support Files\Contents\Windows\Scripts"

I can see the all the foldered scripts, but can't use them

**Comment by majman** [comment]
@SoskiKrota is `C:\Program Files\Adobe\Adobe Illustrator CC 2017\Support Files\Contents\Windows\Scripts` the right location where your scripts are? 

and those scripts are showing up in the panel, but not executing? 

unfortunately i don't have a windows machine to test with, but I'm wondering if it might just be a windows path issue.

**Comment by majman** [comment]
should be fixed by https://github.com/majman/adobe-scripts-panel/pull/5
